mod proc;
// mod sqm; // TODO: generated by kb-port

use anyhow::Result;
use axum::{
    Router,
    extract::{Request, State},
    http::StatusCode,
    response::{IntoResponse, Response},
    routing::get,
    body::Body,
};
use hyper_util::client::legacy::Client;
use hyper_util::rt::TokioExecutor;
use std::sync::Arc;
use tracing::info;

const LISTEN_ADDR: &str = "0.0.0.0:80"; // [1]
const UHTTPD_ADDR: &str = "http://127.0.0.1:8080"; // [2]
const LUCI_AUTH_CHECK: &str = "http://127.0.0.1:8080/cgi-bin/luci/"; // [3]

#[derive(Clone)]
struct AppState {
    http_client: Arc<Client< // [4]
        hyper_util::client::legacy::connect::HttpConnector,
        http_body_util::Full<bytes::Bytes>,
    >>,
}

#[tokio::main]
async fn main() -> Result<()> { // [5]
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::from_default_env()
                .add_directive("kernbridge=info".parse()?),
        )
        .init(); // [6]

    let http_client = Client::builder(TokioExecutor::new()).build_http(); // [7]

    let state = AppState {
        http_client: Arc::new(http_client),
    };

    let app = Router::new()
        .route(
            "/cgi-bin/luci/admin/system/processes",
            get(proc_handler), // [8]
        )
        .route(
            "/cgi-bin/luci/admin/system/processes/kill/:pid",
            axum::routing::post(proc_kill_handler), // [9]
        )
        // TODO: kb-port generated routes go here
        .fallback(proxy_handler) // [10]
        .with_state(state);

    info!("Kernbridge listening on {}", LISTEN_ADDR);
    info!("Forwarding unmatched routes to {}", UHTTPD_ADDR);

    let listener = tokio::net::TcpListener::bind(LISTEN_ADDR).await?;
    axum::serve(listener, app).await?;

    Ok(())
}

async fn is_authenticated( // [11]
    req_headers: &axum::http::HeaderMap,
    http_client: &Client<
        hyper_util::client::legacy::connect::HttpConnector,
        http_body_util::Full<bytes::Bytes>,
    >,
) -> bool {
    let mut auth_req = hyper::Request::builder()
        .method("GET")
        .uri(LUCI_AUTH_CHECK);

    if let Some(cookie) = req_headers.get("cookie") { // [12]
        auth_req = auth_req.header("cookie", cookie);
    }

    let auth_req = match auth_req.body(
        http_body_util::Full::new(bytes::Bytes::new())
    ) {
        Ok(r) => r,
        Err(_) => return false, // [13]
    };

    match http_client.request(auth_req).await {
        Ok(resp) => resp.status() == 200, // [14]
        Err(_) => false, // [15]
    }
}

fn unauthorized() -> Response { // [16]
    axum::response::Redirect::to("/cgi-bin/luci/").into_response()
}

async fn proc_handler( // [17]
    State(state): State<AppState>,
    req: Request,
) -> impl IntoResponse {
    use askama::Template;

    #[derive(Template)]
    #[template(path = "proc/index.html")]
    struct ProcTemplate {
        processes:     Vec<proc::Process>,
        process_count: usize,
        total_ram_mb:  u64,
        timestamp:     String,
    }

    let headers = req.headers().clone();
    if !is_authenticated(&headers, &state.http_client).await {
        return unauthorized();
    }

    let processes = proc::read_processes();
    let tmpl = ProcTemplate {
        total_ram_mb:  processes.iter().map(|p| p.vmrss).sum::<u64>() / 1024, // [18]
        process_count: processes.len(),
        timestamp:     chrono::Local::now().format("%Y-%m-%d %H:%M:%S").to_string(), // [19]
        processes,
    };

    match tmpl.render() {
        Ok(html) => axum::response::Html(html).into_response(),
        Err(e) => {
            tracing::error!("Template error: {}", e);
            (StatusCode::INTERNAL_SERVER_ERROR, "Template error").into_response() // [20]
        }
    }
}

async fn proc_kill_handler( // [21]
    State(state): State<AppState>,
    axum::extract::Path(pid): axum::extract::Path<u32>,
    req: Request,
) -> impl IntoResponse {
    let headers = req.headers().clone();
    if !is_authenticated(&headers, &state.http_client).await {
        return unauthorized();
    }

    match proc::kill_process(pid) {
        Ok(_) => {
            info!("Process {} terminated", pid);
            axum::response::Redirect::to(
                "/cgi-bin/luci/admin/system/processes"
            ).into_response()
        }
        Err(e) => {
            tracing::error!("Kill failed for PID {}: {}", pid, e);
            (StatusCode::INTERNAL_SERVER_ERROR, e).into_response() // [22]
        }
    }
}

async fn proxy_handler( // [23]
    State(state): State<AppState>,
    req: Request,
) -> impl IntoResponse {
    let path = req.uri().path_and_query()
        .map(|p| p.as_str())
        .unwrap_or("/");

    let target_url = format!("{}{}", UHTTPD_ADDR, path); // [24]
    let (parts, body) = req.into_parts(); // [25]

    let body_bytes = match axum::body::to_bytes(body, 1024 * 1024).await { // [26]
        Ok(b) => b,
        Err(e) => {
            tracing::error!("Failed to read request body: {}", e);
            return StatusCode::BAD_REQUEST.into_response();
        }
    };

    let mut proxy_req = hyper::Request::builder()
        .method(parts.method)
        .uri(&target_url);

    for (key, value) in &parts.headers { // [27]
        proxy_req = proxy_req.header(key, value);
    }

    let proxy_req = match proxy_req.body(
        http_body_util::Full::new(bytes::Bytes::from(body_bytes))
    ) {
        Ok(r) => r,
        Err(e) => {
            tracing::error!("Failed to build request: {}", e);
            return StatusCode::BAD_GATEWAY.into_response();
        }
    };

    match state.http_client.request(proxy_req).await {
        Ok(resp) => {
            let status = resp.status();
            let headers = resp.headers().clone();
            let resp_body = Body::new(resp.into_body());
            let mut response = Response::new(resp_body);
            *response.status_mut() = status;
            *response.headers_mut() = headers; // [28]
            response
        }
        Err(e) => {
            tracing::error!("Passthrough error for {}: {}", target_url, e);
            StatusCode::BAD_GATEWAY.into_response() // [29]
        }
    }
}
