// mod proc; // TODO: restore when template is ready
// mod sqm;  // TODO: generated by kb-port

use anyhow::Result;
use axum::{
    Router,
    extract::{Request, State},
    http::{StatusCode, header},
    middleware::{self, Next},
    response::{IntoResponse, Response},
    body::Body,
};
use hyper_util::client::legacy::Client;
use hyper_util::rt::TokioExecutor;
use std::sync::Arc;
use tracing::info;

const LISTEN_ADDR: &str    = "0.0.0.0:80";
const UHTTPD_ADDR: &str    = "http://127.0.0.1:8080"; // [1]
const LUCI_AUTH_CHECK: &str = "http://127.0.0.1:8080/cgi-bin/luci/"; // [2]
const BODY_LIMIT: usize    = 16 * 1024 * 1024; // [3] 16MB for apk/opkg uploads

const FILTERED_REQ_HEADERS: &[&str] = &[ // [4]
    "host",
    "connection",
    "transfer-encoding",
    "te",
    "trailer",
    "upgrade",
];

const FILTERED_RESP_HEADERS: &[&str] = &[ // [5]
    "connection",
    "transfer-encoding",
    "te",
    "trailer",
    "upgrade",
];

#[derive(Clone)]
struct AppState {
    http_client: Arc<Client< // [6]
        hyper_util::client::legacy::connect::HttpConnector,
        http_body_util::Full<bytes::Bytes>,
    >>,
}

#[tokio::main]
async fn main() -> Result<()> { // [7]
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::from_default_env()
                .add_directive("kernbridge=info".parse()?),
        )
        .init(); // [8]

    let http_client = Client::builder(TokioExecutor::new()).build_http(); // [9]

    let state = AppState {
        http_client: Arc::new(http_client),
    };

    let protected = Router::new()
        // TODO: kb-port generated routes go here
        .layer(middleware::from_fn_with_state(state.clone(), auth_middleware)); // [10]

    let app = protected
        .fallback(proxy_handler) // [11]
        .with_state(state);

    info!("Kernbridge listening on {}", LISTEN_ADDR);
    info!("Forwarding unmatched routes to {}", UHTTPD_ADDR);

    let listener = tokio::net::TcpListener::bind(LISTEN_ADDR).await?;
    axum::serve(listener, app).await?;

    Ok(())
}

async fn auth_middleware( // [12]
    State(state): State<AppState>,
    req: Request,
    next: Next,
) -> Response {
    if is_authenticated(req.headers(), &state.http_client).await {
        next.run(req).await // [13]
    } else {
        unauthorized() // [14]
    }
}

async fn is_authenticated( // [15]
    req_headers: &axum::http::HeaderMap,
    http_client: &Client<
        hyper_util::client::legacy::connect::HttpConnector,
        http_body_util::Full<bytes::Bytes>,
    >,
) -> bool {
    let mut auth_req = hyper::Request::builder()
        .method("GET")
        .uri(LUCI_AUTH_CHECK);

    if let Some(cookie) = req_headers.get(header::COOKIE) { // [16]
        auth_req = auth_req.header(header::COOKIE, cookie);
    }

    let auth_req = match auth_req.body(
        http_body_util::Full::new(bytes::Bytes::new())
    ) {
        Ok(r) => r,
        Err(e) => {
            tracing::error!("Failed to build auth request: {}", e); // [17]
            return false;
        }
    };

    match http_client.request(auth_req).await {
        Ok(resp) => resp.status() == 200, // [18]
        Err(e) => {
            tracing::error!("Auth check failed: {}", e); // [19]
            false
        }
    }
}

fn unauthorized() -> Response { // [20]
    axum::response::Redirect::to("/cgi-bin/luci/").into_response()
}

async fn proxy_handler( // [21]
    State(state): State<AppState>,
    req: Request,
) -> impl IntoResponse {
    let path = req.uri().path_and_query()
        .map(|p| p.as_str())
        .unwrap_or("/");

    let target_url = format!("{}{}", UHTTPD_ADDR, path); // [22]
    let (parts, body) = req.into_parts(); // [23]

    let body_bytes = match axum::body::to_bytes(body, BODY_LIMIT).await { // [24]
        Ok(b) => b,
        Err(e) => {
            tracing::error!("Failed to read request body: {}", e);
            return StatusCode::BAD_REQUEST.into_response();
        }
    };

    let mut proxy_req = hyper::Request::builder()
        .method(parts.method)
        .uri(&target_url);

    for (key, value) in &parts.headers { // [25]
        if !FILTERED_REQ_HEADERS.contains(&key.as_str()) {
            proxy_req = proxy_req.header(key, value);
        }
    }

    let proxy_req = match proxy_req.body(
        http_body_util::Full::new(bytes::Bytes::from(body_bytes))
    ) {
        Ok(r) => r,
        Err(e) => {
            tracing::error!("Failed to build proxy request: {}", e);
            return StatusCode::BAD_GATEWAY.into_response();
        }
    };

    match state.http_client.request(proxy_req).await {
        Ok(resp) => {
            let status = resp.status();
            let mut response_headers = resp.headers().clone();
            let resp_body = Body::new(resp.into_body());
            let mut response = Response::new(resp_body);

            for key in FILTERED_RESP_HEADERS { // [26]
                response_headers.remove(*key);
            }

            *response.status_mut() = status;
            *response.headers_mut() = response_headers; // [27]
            response
        }
        Err(e) => {
            tracing::error!("Passthrough error for {}: {}", target_url, e);
            StatusCode::BAD_GATEWAY.into_response() // [28]
        }
    }
}
